
debug: false
management.endpoints.web.exposure.include: "*"
logging:
  level:
    org.springframework.web.servlet: debug
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chris
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true



